#include "../include/STD_Types.h"
#include "../include/BIT_Math.h"
#include "../include/MRCC_interface.h"
#include "../include/MGPIO_interface.h"
#include "../include/MSPI_interface.h"

int main(){

	MRCC_vInit();
	MRCC_vEnablePeripheralClock(RCC_GPIOA);
	MRCC_vEnablePeripheralClock(RCC_SPI1);

	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN0,GPIO_MODE_INPUT);
	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN1,GPIO_MODE_INPUT);
	MGPIO_vSetPinInPutPull(GPIO_PORTA,GPIO_PIN0,GPIO_PULL_UP);
	MGPIO_vSetPinInPutPull(GPIO_PORTA,GPIO_PIN1,GPIO_PULL_UP);

	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN2,GPIO_MODE_OUTPUT);
	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN3,GPIO_MODE_OUTPUT);
	MGPIO_vSetPinOutPutType(GPIO_PORTA,GPIO_PIN2,GPIO_PUSHPULL);
	MGPIO_vSetPinOutPutType(GPIO_PORTA,GPIO_PIN3,GPIO_PUSHPULL);
	MGPIO_vSetPinOutPutSpeed(GPIO_PORTA,GPIO_PIN2,GPIO_MEDIUM_SPEED);
	MGPIO_vSetPinOutPutSpeed(GPIO_PORTA,GPIO_PIN3,GPIO_MEDIUM_SPEED);
	MGPIO_vSetPinValue(GPIO_PORTA,GPIO_PIN2,GPIO_HIGH);
	MGPIO_vSetPinValue(GPIO_PORTA,GPIO_PIN3,GPIO_HIGH);

	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN4,GPIO_MODE_ALTFUN);
	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN5,GPIO_MODE_ALTFUN);
	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN6,GPIO_MODE_ALTFUN);
	MGPIO_vSetPinMode(GPIO_PORTA,GPIO_PIN7,GPIO_MODE_ALTFUN);
	MGPIO_vSetAlternativeFunction(GPIO_PORTA,GPIO_PIN4,ALTFUN_5);
	MGPIO_vSetAlternativeFunction(GPIO_PORTA,GPIO_PIN5,ALTFUN_5);
	MGPIO_vSetAlternativeFunction(GPIO_PORTA,GPIO_PIN6,ALTFUN_5);
	MGPIO_vSetAlternativeFunction(GPIO_PORTA,GPIO_PIN7,ALTFUN_5);

	MSPI_VInit(SPI_MASTER);




	return 0;
}
